services:
  app:
    image: ghcr.io/splooshai/hello-world:latest
    container_name: hello-world
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - hello-world-network

networks:
  hello-world-network:
    driver: bridge
