version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/splooshai/hello-world:latest
    container_name: hello-world
    restart: unless-stopped
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - hello-world-network

networks:
  hello-world-network:
    driver: bridge
